/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ellio' at '3/29/16 7:56 PM' with Gradle 2.10
 *
 * @author ellio, @date 3/29/16 7:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
